using System.Net;
using System.Text;
using MeshScreenDiag.Core.Analysis;
using MeshScreenDiag.Core.Models;

namespace MeshScreenDiag.Core.Reporting;

/// <summary>Builds a single self-contained HTML file (no external resources) that can be e-mailed or attached to a ticket.</summary>
public sealed class HtmlReportBuilder
{
    private readonly DiagnosticReport _r;
    private readonly StringBuilder _sb = new();
    private readonly List<string> _redactions = new();

    public HtmlReportBuilder(DiagnosticReport report)
    {
        _r = report;
        if (report.TitlesRedacted)
        {
            _redactions = new[] { report.Current, report.Baseline, report.After }
                .Where(s => s != null)
                .SelectMany(s => s!.Windows.Select(w => w.Title))
                .Where(t => t.Length >= 3)
                .Distinct()
                .OrderByDescending(t => t.Length)
                .ToList();
        }
    }

    /// <param name="autoRefreshSeconds">When set, the page reloads itself (used by the live web view).</param>
    public string Build(int? autoRefreshSeconds = null)
    {
        var c = _r.Current;
        _sb.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        _sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        if (autoRefreshSeconds is { } s) _sb.Append($"<meta http-equiv=\"refresh\" content=\"{s}\">");
        _sb.Append($"<title>Screen diagnostic — {E(c.MachineName)} — {_r.GeneratedUtc.ToLocalTime():yyyy-MM-dd HH:mm}</title>");
        _sb.Append("<style>").Append(Css).Append("</style></head><body>");

        _sb.Append("<header><h1>MeshCentral Screen Visibility Diagnostic</h1>");
        _sb.Append($"<div class=\"meta\">Computer <b>{E(c.MachineName)}</b> · user {E(c.UserName)} · {E(c.OsVersion)} · session {c.OwnSessionId} · " +
                   $"{(c.IsElevated ? "administrator" : "<span class=\"warn\">not elevated</span>")} · generated {_r.GeneratedUtc.ToLocalTime():yyyy-MM-dd HH:mm:ss} " +
                   $"(UTC{TimeZoneInfo.Local.GetUtcOffset(_r.GeneratedUtc):hh\\:mm}) · tool v{E(_r.ToolVersion)}</div>");
        _sb.Append("<nav>");
        foreach (var (id, label) in new[] { ("summary", "Summary"), ("findings", "Findings"), ("mesh", "MeshCentral"), ("capture", "Capture & display"), ("timeline", "Timeline"), ("compare", "Before / after"), ("network", "Network"), ("security", "Security & firewall"), ("events", "Event logs"), ("processes", "Processes"), ("services", "Services & drivers"), ("limits", "Limitations") })
            _sb.Append($"<a href=\"#{id}\">{label}</a>");
        _sb.Append("</nav></header><main>");

        Summary();
        Findings();
        Mesh();
        CaptureAndDisplay();
        Timeline();
        Compare();
        Network();
        Security();
        Events();
        Processes();
        ServicesAndDrivers();
        Limitations();

        _sb.Append("</main><footer>Generated by MeshScreenDiag — read-only diagnostic; no settings were changed on this computer.</footer></body></html>");
        return _sb.ToString();
    }

    // ---------------------------------------------------------------------------------------------
    private void Summary()
    {
        var v = _r.Verdict;
        var c = _r.Current;
        Section("summary", "Summary");
        _sb.Append($"<div class=\"verdict {(v.PrimaryCause != null ? "bad" : c.Capture?.AnyBlack == true ? "bad" : "ok")}\"><div class=\"big\">{E(v.Headline)}</div></div>");
        _sb.Append("<div class=\"tiles\">");
        Tile("Connection vs capture", v.ConnectionVsCapture, v.ConnectionVsCapture.StartsWith("CAPTURE") || v.ConnectionVsCapture.StartsWith("CONNECTION") ? "bad" : "neutral");
        Tile("MeshCentral agent", c.Mesh?.Health ?? "not collected", c.Mesh?.Health == "CONNECTED" ? "ok" : "bad");
        Tile("Screen capture test", c.Capture?.Summary ?? "not run", c.Capture == null ? "neutral" : c.Capture.AnyBlack || c.Capture.AnyFailed ? "bad" : "ok");
        var desk = c.Display == null ? "unknown" : c.Display.InputDesktopAccessible ? c.Display.InputDesktopName ?? "?" : "Secure desktop (inaccessible)";
        Tile("Input desktop", desk, c.Display?.IsOnAlternateDesktop == true ? "bad" : "ok");
        var prot = c.Windows.Count(w => w.IsCaptureProtected && !w.IsMinimized);
        Tile("Capture-protected windows", prot.ToString(), prot > 0 ? "bad" : "ok");
        Tile("Markers", _r.Markers.Count == 0 ? "none" : string.Join(", ", _r.Markers.Select(m => m.TimeUtc.ToLocalTime().ToString("HH:mm:ss") + (m.Automatic ? " (auto)" : ""))), "neutral");
        _sb.Append("</div>");
        _sb.Append($"<p class=\"detail\">{E(v.ConnectionVsCaptureDetail)}</p>");

        if (v.Scores.Any(s => s.Score > 0))
        {
            _sb.Append("<h3>Cause likelihood</h3><table class=\"scores\">");
            foreach (var s in v.Scores.Where(s => s.Score > 0))
                _sb.Append($"<tr><td>{E(s.Label)}</td><td class=\"bar\"><div style=\"width:{s.Score}%\"></div></td><td>{s.Score}</td></tr>");
            _sb.Append("</table>");
        }

        if (v.SuspectApplications.Count > 0)
        {
            _sb.Append("<h3>Applications started around the black-screen moment</h3><ul class=\"mono\">");
            foreach (var s in v.SuspectApplications) _sb.Append($"<li>{E(s)}</li>");
            _sb.Append("</ul>");
        }

        if (!string.IsNullOrWhiteSpace(_r.TechnicianNotes))
            _sb.Append($"<h3>Technician notes</h3><pre>{E(_r.TechnicianNotes!)}</pre>");
        _sb.Append("</section>");
    }

    private void Findings()
    {
        Section("findings", $"Findings ({_r.Verdict.Findings.Count})");
        foreach (var f in _r.Verdict.Findings)
        {
            _sb.Append($"<div class=\"finding sev-{f.Severity.ToString().ToLowerInvariant()}\">");
            _sb.Append($"<div class=\"fhead\"><span class=\"badge\">{f.Severity}</span> <span class=\"cat\">{E(CategoryLabels.Of(f.Category))}</span> <b>{E(f.Title)}</b></div>");
            _sb.Append($"<p>{E(f.Explanation)}</p>");
            if (f.Evidence.Count > 0)
            {
                _sb.Append("<div class=\"evidence\"><b>Evidence</b><ul>");
                foreach (var e in f.Evidence) _sb.Append($"<li>{E(e)}</li>");
                _sb.Append("</ul></div>");
            }
            if (!string.IsNullOrEmpty(f.Recommendation)) _sb.Append($"<p class=\"rec\"><b>Recommendation:</b> {E(f.Recommendation)}</p>");
            _sb.Append("</div>");
        }
        _sb.Append("</section>");
    }

    private void Mesh()
    {
        var m = _r.Current.Mesh;
        Section("mesh", "MeshCentral agent");
        if (m == null) { _sb.Append("<p>Not collected.</p></section>"); return; }
        KeyValues(new()
        {
            ["Health"] = m.Health,
            ["Service"] = $"{m.ServiceName ?? "(not found)"} — {m.ServiceState ?? "?"} / {m.ServiceStartMode ?? "?"}",
            ["Install path"] = m.InstallPath ?? "?",
            ["Server URL (.msh)"] = m.ServerUrl ?? "(unknown)",
            ["Server addresses"] = m.ServerAddresses.Count > 0 ? string.Join(", ", m.ServerAddresses) : "(not resolved)",
            ["Mesh (device group)"] = m.MeshName ?? "?",
            ["Established connections"] = m.EstablishedCount.ToString(),
            ["Remote desktop (KVM) process"] = m.KvmActive ? "running" : "not running",
        });
        if (m.Processes.Count > 0)
        {
            Table(new[] { "Role", "PID", "Name", "Session", "CPU", "I/O rate", "Started", "Command line / path" },
                m.Processes.Select(p => new[]
                {
                    p.Role, p.Pid.ToString(), p.Name, p.SessionId.ToString(),
                    p.CpuPercent != null ? $"{p.CpuPercent:F1}%" : "n/a",
                    p.IoBytesPerSec != null ? AnalysisEngine.FormatRate(p.IoBytesPerSec.Value) : "n/a",
                    p.StartTimeUtc?.ToLocalTime().ToString("HH:mm:ss") ?? "", p.CommandLine ?? p.Path ?? "",
                }));
        }
        if (m.Connections.Count > 0)
        {
            _sb.Append("<h3>Agent network endpoints</h3>");
            ConnectionTable(m.Connections);
        }
        if (m.Notes.Count > 0)
        {
            _sb.Append("<ul>");
            foreach (var n in m.Notes) _sb.Append($"<li>{E(n)}</li>");
            _sb.Append("</ul>");
        }
        _sb.Append("</section>");
    }

    private void CaptureAndDisplay()
    {
        var c = _r.Current;
        Section("capture", "Screen capture & display");
        if (c.Capture != null)
        {
            _sb.Append($"<p>Method: {E(c.Capture.Method)} at {c.Capture.TimeUtc.ToLocalTime():HH:mm:ss}</p>");
            Table(new[] { "Region", "Bounds", "Result", "Black pixels", "Mean luminance", "Colours" },
                c.Capture.Monitors.Concat(c.Capture.ProtectedWindows).Select(m => new[]
                {
                    m.Name, m.Bounds.ToString(), m.StatusText, m.Succeeded ? m.BlackRatio.ToString("P1") : "", m.Succeeded ? m.MeanLuminance.ToString("F1") : "", m.Succeeded ? m.DistinctColors.ToString() : "",
                }), rowClass: i => i < c.Capture.Monitors.Count && c.Capture.Monitors[i].IsBlack ? "hl" : null);
        }

        if (c.Display is { } d)
        {
            KeyValues(new()
            {
                ["Input desktop"] = d.InputDesktopAccessible ? d.InputDesktopName ?? "?" : $"not accessible (error {d.InputDesktopError}) — secure desktop",
                ["This process's desktop"] = d.OwnDesktopName ?? "?",
                ["User notification state"] = d.NotificationState,
                ["Session"] = $"own {d.OwnSessionId} ({d.OwnSessionConnectState}), console {d.ActiveConsoleSessionId}, locked {d.SessionLocked?.ToString() ?? "?"}, remote (RDP) {d.IsRemoteSession}",
                ["Multi-plane overlay (MPO)"] = d.MpoDisabled == true ? "disabled (OverlayTestMode=5)" : d.MpoDisabled == false ? "enabled (default)" : "unknown",
                ["HW-accelerated GPU scheduling"] = d.HagsMode switch { 2 => "on", 1 => "off", null => "unknown", _ => d.HagsMode.ToString()! },
            });
            _sb.Append("<h3>Monitors</h3>");
            Table(new[] { "Device", "Bounds", "Primary", "Bits/pixel", "Refresh" },
                d.Monitors.Select(m => new[] { m.DeviceName, m.Bounds.ToString(), m.IsPrimary ? "yes" : "", m.BitsPerPixel.ToString(), $"{m.RefreshRateHz} Hz" }));
            if (d.Adapters.Count > 0)
            {
                _sb.Append("<h3>Display adapters</h3>");
                Table(new[] { "Adapter", "Vendor", "Driver", "Driver date", "Status", "Mode" },
                    d.Adapters.Select(a => new[] { a.Name, a.Vendor ?? "", a.DriverVersion ?? "", a.DriverDate ?? "", a.Status ?? "", a.CurrentMode ?? "" }));
            }
        }

        _sb.Append("<h3>Visible top-level windows</h3>");
        Table(new[] { "Process", "PID", "Title", "Class", "Bounds", "Monitor coverage", "Display affinity", "Flags" },
            _r.Current.Windows.OrderByDescending(w => w.IsCaptureProtected).ThenByDescending(w => w.MaxMonitorCoverage).Take(150).Select(w => new[]
            {
                w.ProcessName, w.Pid.ToString(), w.Title, w.ClassName, w.Bounds.ToString(), w.MaxMonitorCoverage.ToString("P0"), w.AffinityDisplay,
                string.Join(" ", new[] { w.IsForeground ? "foreground" : null, w.IsTopMost ? "topmost" : null, w.IsLayered ? "layered" : null, w.IsClickThrough ? "click-through" : null, w.IsMinimized ? "minimized" : null, w.IsHung ? "HUNG" : null, w.IsCloaked ? "cloaked" : null }.Where(x => x != null)),
            }), rowClass: i => null, highlight: row => row[6] != "None");
        _sb.Append("</section>");
    }

    private void Timeline()
    {
        Section("timeline", "Timeline");
        var markers = _r.Markers.OrderBy(m => m.TimeUtc).ToList();
        var all = _r.Timeline.OrderBy(e => e.TimeUtc).ToList();
        bool Near(DateTime t) => markers.Any(m => t >= m.TimeUtc - _r.CorrelationWindow && t <= m.TimeUtc + TimeSpan.FromSeconds(30));

        if (markers.Count > 0)
        {
            _sb.Append($"<p>Rows within {_r.CorrelationWindow.TotalSeconds:F0}s before / 30s after a black-screen marker are highlighted. Informational process events outside that window are omitted.</p>");
        }
        var rows = all.Where(e => e.Severity >= Severity.Low || Near(e.TimeUtc) || e.Source == "User").TakeLast(3000).ToList();
        _sb.Append("<table class=\"grid timeline\"><thead><tr><th>Time</th><th>Severity</th><th>Category</th><th>Event</th></tr></thead><tbody>");
        var mi = 0;
        foreach (var e in rows)
        {
            while (mi < markers.Count && markers[mi].TimeUtc <= e.TimeUtc)
            {
                MarkerRow(markers[mi]);
                mi++;
            }
            var cls = Near(e.TimeUtc) ? " class=\"hl\"" : "";
            _sb.Append($"<tr{cls}><td class=\"nowrap\">{e.TimeUtc.ToLocalTime():HH:mm:ss}</td><td><span class=\"sev sev-{e.Severity.ToString().ToLowerInvariant()}\">{e.Severity}</span></td><td>{E(e.Category)}</td><td>{E(e.Title)}</td></tr>");
        }
        for (; mi < markers.Count; mi++) MarkerRow(markers[mi]);
        _sb.Append("</tbody></table></section>");
    }

    private void MarkerRow(BlackScreenMarker m) =>
        _sb.Append($"<tr class=\"marker\"><td class=\"nowrap\">{m.TimeUtc.ToLocalTime():HH:mm:ss}</td><td colspan=\"3\">■ BLACK SCREEN MARKED{(m.Automatic ? " (auto-detected)" : "")}{(string.IsNullOrEmpty(m.Note) ? "" : " — " + E(m.Note))}</td></tr>");

    private void Compare()
    {
        Section("compare", "Before / after comparison");
        var d = _r.Diff;
        if (d == null)
        {
            _sb.Append("<p>No baseline was captured. Use <b>Take baseline</b> before the client launches the application, then <b>Take 'after' snapshot</b> (or mark the black screen) to get a full comparison.</p></section>");
            return;
        }
        _sb.Append($"<p>Before: <b>{E(d.BeforeLabel)}</b> at {d.BeforeUtc.ToLocalTime():HH:mm:ss} → After: <b>{E(d.AfterLabel)}</b> at {d.AfterUtc.ToLocalTime():HH:mm:ss} — {d.Items.Count} change(s).</p>");
        foreach (var g in d.ByArea())
        {
            _sb.Append($"<details open><summary>{E(g.Key)} ({g.Count()})</summary><table class=\"grid\"><tbody>");
            foreach (var i in g)
                _sb.Append($"<tr><td><span class=\"sev sev-{i.Severity.ToString().ToLowerInvariant()}\">{i.Severity}</span></td><td>{i.Change}</td><td>{E(i.Description)}</td></tr>");
            _sb.Append("</tbody></table></details>");
        }
        _sb.Append("</section>");
    }

    private void Network()
    {
        Section("network", "Network ports & connections");
        var conns = _r.Current.Connections;
        _sb.Append($"<p>{conns.Count(c => c.Protocol == "TCP" && c.IsEstablished)} established TCP connections, {conns.Count(c => c.Protocol == "TCP" && c.State == "LISTEN")} TCP listeners, {conns.Count(c => c.Protocol == "UDP")} UDP endpoints.</p>");
        _sb.Append("<h3>Listening ports</h3>");
        ConnectionTable(conns.Where(c => c.IsListening).OrderBy(c => c.Protocol).ThenBy(c => c.LocalPort));
        _sb.Append("<h3>Active connections</h3>");
        ConnectionTable(conns.Where(c => !c.IsListening).OrderByDescending(c => c.IsMeshAgent).ThenBy(c => c.ProcessName));
        _sb.Append("</section>");
    }

    private void ConnectionTable(IEnumerable<NetConnection> conns) =>
        Table(new[] { "Proto", "Local", "Remote", "State", "PID", "Process", "Purpose", "Executable" },
            conns.Select(c => new[]
            {
                c.Protocol + (c.IpVersion == 6 ? "v6" : ""), $"{c.LocalAddress}:{c.LocalPort}",
                c.Protocol == "UDP" ? "" : $"{c.RemoteAddress}:{c.RemotePort}", c.State, c.Pid.ToString(), c.ProcessName, c.Purpose, c.ProcessPath ?? "",
            }), highlight: row => false, rowClassFromData: conns.Select(c => c.IsMeshAgent ? "mesh" : null).ToList());

    private void Security()
    {
        var c = _r.Current;
        Section("security", "Security software & firewall");
        if (c.SecurityProducts.Count > 0)
        {
            Table(new[] { "Type", "Product", "Enabled", "Up to date", "State", "Executable" },
                c.SecurityProducts.Select(p => new[] { p.Kind, p.Name, p.Enabled ? "yes" : "NO", p.UpToDate ? "yes" : "no", $"0x{p.ProductState:X6}", p.ExecutablePath ?? "" }));
        }
        else _sb.Append("<p>No products reported by Windows Security Center (normal on Windows Server).</p>");
        if (c.Defender is { } def)
            KeyValues(new()
            {
                ["Defender antivirus"] = def.AntivirusEnabled?.ToString() ?? "?",
                ["Real-time protection"] = def.RealTimeProtectionEnabled?.ToString() ?? "?",
                ["Behaviour monitoring"] = def.BehaviorMonitorEnabled?.ToString() ?? "?",
                ["Tamper protection"] = def.IsTamperProtected?.ToString() ?? "?",
                ["Version"] = def.ProductVersion ?? def.Error ?? "?",
            });

        var fw = c.Firewall;
        _sb.Append("<h3>Windows Firewall</h3>");
        if (fw == null) { _sb.Append("<p>Not collected.</p></section>"); return; }
        if (fw.Error != null) _sb.Append($"<p class=\"warn\">{E(fw.Error)}</p>");
        Table(new[] { "Profile", "Active", "Enabled", "Default inbound", "Default outbound", "Block all inbound" },
            fw.Profiles.Select(p => new[] { p.Name, p.IsActive ? "yes" : "", p.Enabled ? "yes" : "NO", p.DefaultInboundAction, p.DefaultOutboundAction, p.BlockAllInbound ? "yes" : "" }));
        var relevant = fw.Rules.Where(r => SnapshotComparer.IsMeshName(r.Application) || SnapshotComparer.IsMeshName(r.Name)).ToList();
        _sb.Append($"<h3>Rules that mention the MeshCentral agent ({relevant.Count})</h3>");
        RuleTable(relevant);
        var blocks = fw.Rules.Where(r => r.Enabled && r.Action == "Block").ToList();
        _sb.Append($"<details><summary>All enabled BLOCK rules ({blocks.Count} of {fw.Rules.Count} rules)</summary>");
        RuleTable(blocks);
        _sb.Append("</details></section>");
    }

    private void RuleTable(IEnumerable<FirewallRuleInfo> rules) =>
        Table(new[] { "Name", "Enabled", "Dir", "Action", "Protocol", "Local ports", "Remote ports", "Remote addresses", "Program / service", "Profiles" },
            rules.Select(r => new[] { r.Name, r.Enabled ? "yes" : "no", r.Direction, r.Action, r.Protocol, r.LocalPorts ?? "", r.RemotePorts ?? "", r.RemoteAddresses ?? "", r.Application ?? r.Service ?? "", r.Profiles }),
            highlight: row => row[3] == "Block" && row[1] == "yes");

    private void Events()
    {
        Section("events", "Relevant Windows event-log entries");
        var events = _r.Events.OrderByDescending(e => e.TimeUtc).Take(600).ToList();
        if (events.Count == 0) { _sb.Append("<p>None collected.</p></section>"); return; }
        Table(new[] { "Time", "Log", "Source", "ID", "Level", "Message" },
            events.Select(e => new[] { e.TimeUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"), e.Channel, e.Provider, e.EventId.ToString(), e.Level, e.Message.Length > 400 ? e.Message[..400] + "…" : e.Message }),
            highlight: row => row[5].Contains("mesh", StringComparison.OrdinalIgnoreCase));
        _sb.Append("</section>");
    }

    private void Processes()
    {
        Section("processes", $"Processes ({_r.Current.Processes.Count})");
        _sb.Append("<details><summary>Show all processes</summary>");
        Table(new[] { "PID", "Parent", "Name", "Session", "Started", "Company", "Signer", "Integrity", "Rendering / DRM", "Path" },
            _r.Current.Processes.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase).Select(p => new[]
            {
                p.Pid.ToString(), p.ParentPid.ToString(), p.Name, p.SessionId.ToString(), p.StartTimeUtc?.ToLocalTime().ToString("MM-dd HH:mm:ss") ?? "",
                p.Company ?? "", p.Signer ?? "", p.IntegrityLevel ?? "", string.Join(", ", p.ModuleIndicators), p.Path ?? "",
            }));
        _sb.Append("</details></section>");
    }

    private void ServicesAndDrivers()
    {
        var c = _r.Current;
        Section("services", "Services & drivers");
        var svcs = c.Services.Where(s => s.Type == "Service").ToList();
        _sb.Append($"<details><summary>Services ({svcs.Count}, {svcs.Count(s => s.State == "Running")} running)</summary>");
        Table(new[] { "Name", "Display name", "State", "Start", "PID", "Path" },
            svcs.OrderBy(s => s.Name).Select(s => new[] { s.Name, s.DisplayName, s.State, s.StartMode, s.ProcessId.ToString(), s.PathName ?? "" }),
            highlight: row => SnapshotComparer.IsMeshName(row[0]) || SnapshotComparer.IsMeshName(row[5]));
        _sb.Append("</details>");
        var drvs = c.Services.Where(s => s.Type == "Driver").ToList();
        _sb.Append($"<details><summary>Registered drivers ({drvs.Count}, {drvs.Count(s => s.State == "Running")} running)</summary>");
        Table(new[] { "Name", "Display name", "State", "Start", "Path" },
            drvs.OrderBy(s => s.Name).Select(s => new[] { s.Name, s.DisplayName, s.State, s.StartMode, s.PathName ?? "" }));
        _sb.Append("</details>");
        _sb.Append($"<details><summary>Loaded kernel modules ({c.LoadedDrivers.Count})</summary>");
        Table(new[] { "Module", "Path" }, c.LoadedDrivers.OrderBy(d => d.Name).Select(d => new[] { d.Name, d.Path ?? "" }));
        _sb.Append("</details></section>");
    }

    private void Limitations()
    {
        Section("limits", "Collection notes & limitations");
        var errs = _r.Current.CollectorErrors.Distinct().ToList();
        _sb.Append("<ul>");
        _sb.Append("<li>The capture test uses GDI BitBlt like the MeshAgent KVM. It runs in this tool's session and desktop; when the input desktop is the secure desktop, only SYSTEM-level capture (as MeshAgent uses) can see it.</li>");
        _sb.Append("<li>Processes that start and exit between two monitoring ticks are only seen through the Security log (event 4688), if process-creation auditing is enabled.</li>");
        if (_r.TitlesRedacted) _sb.Append("<li>Window titles are redacted in this report.</li>");
        foreach (var e in errs) _sb.Append($"<li>{E(e)}</li>");
        _sb.Append("</ul></section>");
    }

    // ---------------------------------------------------------------------------------------------
    private void Section(string id, string title) => _sb.Append($"<section id=\"{id}\"><h2>{E(title)}</h2>");

    private void Tile(string label, string value, string cls) =>
        _sb.Append($"<div class=\"tile {cls}\"><div class=\"lbl\">{E(label)}</div><div class=\"val\">{E(value)}</div></div>");

    private void KeyValues(Dictionary<string, string> kv)
    {
        _sb.Append("<table class=\"kv\">");
        foreach (var (k, v) in kv) _sb.Append($"<tr><th>{E(k)}</th><td>{E(v)}</td></tr>");
        _sb.Append("</table>");
    }

    private void Table(string[] headers, IEnumerable<string[]> rows, Func<int, string?>? rowClass = null, Func<string[], bool>? highlight = null, IReadOnlyList<string?>? rowClassFromData = null)
    {
        _sb.Append("<div class=\"scroll\"><table class=\"grid\"><thead><tr>");
        foreach (var h in headers) _sb.Append($"<th>{E(h)}</th>");
        _sb.Append("</tr></thead><tbody>");
        var i = 0;
        foreach (var row in rows)
        {
            var cls = rowClass?.Invoke(i) ?? (highlight?.Invoke(row) == true ? "hl" : null) ?? (rowClassFromData != null && i < rowClassFromData.Count ? rowClassFromData[i] : null);
            _sb.Append(cls != null ? $"<tr class=\"{cls}\">" : "<tr>");
            foreach (var cell in row) _sb.Append($"<td>{E(cell)}</td>");
            _sb.Append("</tr>");
            i++;
        }
        if (i == 0) _sb.Append($"<tr><td colspan=\"{headers.Length}\" class=\"empty\">none</td></tr>");
        _sb.Append("</tbody></table></div>");
    }

    private string E(string? s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        foreach (var t in _redactions) s = s.Replace(t, "[redacted]", StringComparison.Ordinal);
        return WebUtility.HtmlEncode(s);
    }

    private const string Css = @"
:root{--bg:#f6f7f9;--card:#fff;--fg:#1d2330;--mut:#5b6475;--line:#e2e5ea;--bad:#c62828;--badbg:#fdecea;--ok:#2e7d32;--okbg:#e8f5e9;--hl:#fff8e1;--acc:#1565c0}
*{box-sizing:border-box}body{margin:0;font:14px/1.45 'Segoe UI',system-ui,sans-serif;background:var(--bg);color:var(--fg)}
header{background:#1d2330;color:#fff;padding:16px 24px;position:sticky;top:0;z-index:5}header h1{margin:0 0 4px;font-size:20px}
.meta{color:#c9d1e0;font-size:12.5px}.meta .warn{color:#ffcc80}nav{margin-top:8px;display:flex;flex-wrap:wrap;gap:4px}
nav a{color:#fff;text-decoration:none;background:#2f3950;padding:3px 9px;border-radius:12px;font-size:12px}nav a:hover{background:#43507a}
main{max-width:1500px;margin:0 auto;padding:16px 24px}section{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px 18px;margin:0 0 16px}
h2{margin:0 0 10px;font-size:17px;border-bottom:1px solid var(--line);padding-bottom:6px}h3{font-size:14.5px;margin:14px 0 6px}
.verdict{padding:12px 16px;border-radius:6px;margin-bottom:12px}.verdict.bad{background:var(--badbg);border-left:5px solid var(--bad)}.verdict.ok{background:var(--okbg);border-left:5px solid var(--ok)}
.verdict .big{font-size:16px;font-weight:600}.detail{color:var(--fg)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:8px}.tile{border:1px solid var(--line);border-radius:6px;padding:8px 10px;border-top:4px solid #9aa3b5}
.tile.bad{border-top-color:var(--bad)}.tile.ok{border-top-color:var(--ok)}.tile .lbl{font-size:11.5px;color:var(--mut);text-transform:uppercase;letter-spacing:.03em}.tile .val{font-weight:600;margin-top:2px;word-break:break-word}
.scores td{padding:2px 8px}.scores .bar{width:320px}.scores .bar div{height:10px;background:var(--acc);border-radius:5px}
.finding{border:1px solid var(--line);border-left:5px solid #9aa3b5;border-radius:6px;padding:8px 12px;margin:8px 0}
.finding.sev-critical{border-left-color:#b71c1c}.finding.sev-high{border-left-color:#e65100}.finding.sev-medium{border-left-color:#f9a825}.finding.sev-low{border-left-color:#1565c0}
.finding p{margin:6px 0}.fhead .cat{color:var(--mut);font-size:12px}.badge,.sev{display:inline-block;font-size:11px;font-weight:700;padding:1px 7px;border-radius:9px;background:#9aa3b5;color:#fff}
.sev-critical .badge,.sev.sev-critical{background:#b71c1c}.sev-high .badge,.sev.sev-high{background:#e65100}.sev-medium .badge,.sev.sev-medium{background:#f9a825;color:#222}.sev-low .badge,.sev.sev-low{background:#1565c0}
.evidence ul{margin:4px 0 4px 18px;padding:0;font-family:Consolas,monospace;font-size:12.5px}.rec{background:#f3f6fb;padding:6px 8px;border-radius:4px}
.scroll{overflow-x:auto}table.grid{border-collapse:collapse;width:100%;font-size:12.5px}table.grid th,table.grid td{border-bottom:1px solid var(--line);padding:4px 6px;text-align:left;vertical-align:top}
table.grid th{background:#eef1f5;position:sticky;top:0}table.grid tr.hl td{background:var(--hl)}table.grid tr.mesh td{background:#e3f2fd}
table.grid tr.marker td{background:#b71c1c;color:#fff;font-weight:700}td.empty{color:var(--mut);font-style:italic}.nowrap{white-space:nowrap}
table.kv th{text-align:left;color:var(--mut);font-weight:500;padding:2px 14px 2px 0;vertical-align:top}table.kv td{padding:2px 0}
details summary{cursor:pointer;font-weight:600;margin:6px 0}.mono{font-family:Consolas,monospace;font-size:12.5px}pre{white-space:pre-wrap}
footer{color:var(--mut);font-size:12px;text-align:center;padding:12px}
@media print{header{position:static}details{display:block}details>*{display:block}}
";
}
